BlogSite/Pages/Author/Favorites.cshtml.cs
using BlogSite.Models;
using BlogSite.Models.FilterModels;
using BlogSite.Models.PartialModels;
using BlogSite.Services;
using BlogSite.Services.Filters;
using BlogSite.Services.Filters.Configurators;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogSite.Pages.Author
{
    public class FavoritesModel : PageModel
    {
        private readonly BlogSiteContext db;
        private User? Client { get; set; }

        [BindProperty]
        public PostsFilterModel FilterModel { get; set; }

        public PartialPostsShowcase PostsShowcase { get; private set; }

        public PartialPagination Pagination { get; private set; }

        public List<PartialAuthor> Favorites { get; private set; }

        public FavoritesModel(BlogSiteContext db)
        {
            this.db = db;

            this.InitEmptyModel();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            return await this.RequestHandlerResult();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            return await this.RequestHandlerResult();
        }

        private void InitClient()
        {
            ClientService clientService = new ClientService(TempData);
            this.Client = clientService.GetDeserializedClient();
        }

        private void InitEmptyModel()
        {
            this.FilterModel = new PostsFilterModel();
            this.PostsShowcase = new PartialPostsShowcase();
            this.Pagination = new PartialPagination();
            this.Favorites = new List<PartialAuthor>();
        }

        private async Task<IActionResult> RequestHandlerResult()
        {
            this.InitClient();

            if(this.Client != null) return await FavoritesResult();

            return RedirectToPage("../Authentication/Index");
        }

        private async Task<IActionResult> FavoritesResult()
        {
            try
            {
                AuthorService authorService = new AuthorService(db);
                this.Favorites = await authorService.GetFavoritesAsync(this.Client!.UserId);

                await FilterAsync();

                PostsFilterConfigurator configurator = new PostsFilterConfigurator(db, this.FilterModel);
                await configurator.ConfigureFilterAsync();
            }
            catch(Exception ex)
            {
                this.InitEmptyModel();
                ViewData["ServerMessage"] = new ServerMessage();
            }

            return Page();
        }

        private async Task FilterAsync()
        {
            PostsFilter filter = new PostsFilter(this.db.Posts, FilterModel.FilterData, PostsShowcase.ElementsPerPage);
            filter.BuildStandartFilter();
            filter.FilterByFavorites(this.Client!);

            int total_pages = await filter.GetTotalPagesAsync();

            filter.UsePagination();

            this.PostsShowcase.Posts = await filter.FilterAsync();
            this.Pagination = new PartialPagination(total_pages, FilterModel.FilterData.Page);
        }
    }
}

BlogSite/Pages/Author/Index.cshtml.cs
using BlogSite.Models.FilterModels;
using BlogSite.Models.PartialModels;
using BlogSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BlogSite.Services;
using BlogSite.Services.Filters;
using BlogSite.Services.Filters.Configurators;
using Microsoft.EntityFrameworkCore;

namespace BlogSite.Pages.Author
{
    public class IndexModel : PageModel
    {
        private readonly BlogSiteContext db;

        private User? Client { get; set; }

        [BindProperty]
        public PostsFilterModel FilterModel { get; set; }

        public PartialPostsShowcase PostsShowcase { get; private set; }

        public PartialPagination Pagination { get; private set; }

        public PartialAuthor? Author { get; private set; }

        public bool IsAuthenticated { get { return Client != null; } }

        public bool IsClientBlog { get { return Client!.UserId == Author!.AuthorId; } }

        public IndexModel(BlogSiteContext db)
        {
            this.db = db;

            this.InitEmptyModel();
        }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            return await this.RequestHandlerResult(id);
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            return await this.RequestHandlerResult(id);
        }

        public async Task<IActionResult> OnPostFollowAsync(int author_id)
        {
            try
            {
                this.InitClient();

                if (!IsAuthenticated || this.Client!.UserId == author_id)
                    throw new Exception();

                await db.Database.ExecuteSqlAsync($"insert into FollowersAuthors values({this.Client.UserId},{author_id})");
            }
            catch(Exception ex)
            {
                return Partial("Components/_ButtonFollow", false);
            }

            return Partial("Components/_ButtonFollow", true);
        }

        public async Task<IActionResult> OnPostUnfollowAsync(int author_id)
        {
            try
            {
                this.InitClient();

                if (!IsAuthenticated || this.Client!.UserId == author_id)
                    throw new Exception();

                await db.Database.ExecuteSqlAsync($"delete from FollowersAuthors where Follower = {this.Client.UserId} and Author = {author_id}");
            }
            catch(Exception ex)
            {
                return Partial("Components/_ButtonFollow", true);
            }

            return Partial("Components/_ButtonFollow", false);
        }

        private void InitClient()
        {
            ClientService clientService = new ClientService(TempData);
            this.Client = clientService.GetDeserializedClient();
        }

        private void InitEmptyModel()
        {
            this.FilterModel = new PostsFilterModel();
            this.PostsShowcase = new PartialPostsShowcase();
            this.Pagination = new PartialPagination();
        }

        private async Task<IActionResult> RequestHandlerResult(int author_id)
        {
            this.InitClient();

            if(author_id <= 0)
            {
                if (IsAuthenticated) author_id = this.Client!.UserId;
                else return RedirectToPage("/Authentication/Index");
            }

            return await BlogResult(author_id);
        }

        private async Task<IActionResult> BlogResult(int author_id)
        {
            try
            {
                AuthorService authorService = new AuthorService(this.db);
                this.Author = await authorService.GetPartialAuthorAsync(author_id);

                if (this.Author != null)
                {
                    if(this.Client != null) this.Author.IsFollowed = await authorService.GetFollowStatus(this.Client!.UserId, this.Author.AuthorId);

                    await this.FilterAsync();

                    PostsFilterConfigurator configurator = new PostsFilterConfigurator(db, FilterModel);
                    await configurator.ConfigureFilterAsync();
                }
            }
            catch (Exception ex)
            {
                this.InitEmptyModel();
                ViewData["ServerMessage"] = new ServerMessage();
            }

            return Page();
        }

        private async Task FilterAsync()
        {
            PostsFilter filter = new PostsFilter(this.db.Posts, FilterModel.FilterData, PostsShowcase.ElementsPerPage);
            filter.BuildStandartFilter();
            filter.FilterByAuthor(this.Author!.AuthorId);

            int total_pages = await filter.GetTotalPagesAsync();

            filter.UsePagination();

            this.PostsShowcase.Posts = await filter.FilterAsync();
            this.Pagination = new PartialPagination(total_pages, FilterModel.FilterData.Page);
        }
    }
}

BlogSite/Pages/Author/Settings.cshtml.cs
using BlogSite.Models;
using BlogSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogSite.Pages.Author
{
    public class SettingsModel : PageModel
    {
        private readonly BlogSiteContext db;

        [BindProperty]
        public User Client { get; set; }

        public SettingsModel(BlogSiteContext db)
        {
            this.db = db;
        }

        public IActionResult OnGet()
        {
            ClientService clientService = new ClientService(TempData);
            this.Client = clientService.GetDeserializedClient();

            if (this.Client is null) 
                return RedirectToPage("/Authentication/Index");

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            try
            {
                ClientService clientService = new ClientService(TempData, this.db);
                var client = clientService.GetDeserializedClient();

                if (this.AnyChanges(client)) await clientService.UpdateAsync(this.Client!);

                return RedirectToPage();
            }
            catch(Exception ex)
            {
                ViewData["ServerMessage"] = new ServerMessage();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            try
            {
                ClientService clientService = new ClientService(TempData, this.db);
                var client = clientService.GetDeserializedClient();

                if (client is null)
                    throw new Exception();

                await clientService.DeleteAsync(client);
            }
            catch(Exception ex)
            {
                return new JsonResult(false);
            }

            return new JsonResult(true);
        }

        private bool AnyChanges(User? client)
        {
            if(client != null)
            {
                // these properties are not for change, so they must stay the same
                this.Client.UserId = client.UserId;
                this.Client.Email = client.Email;

                return !this.Client.Equals(client); // if there is no changes => no update request to database
            }

            return false;
        }
    }
}

BlogSite/Pages/Author/Favorites.cshtml
@page
@model BlogSite.Pages.Author.FavoritesModel
@{
    ViewData["Title"] = "Favorites";
}

@if(Model.Favorites.Count > 0)
{
    @section Css{
        <link rel="stylesheet" href="~/css/posts_filter.css" />
        <link rel="stylesheet" href="~/css/partial_post.css" />
        <link rel="stylesheet" href="~/css/favorites_list.css" />
    }

    <div class="container mt-4">
        <div class="row">
            <div class="col-sm-12 col-md-2 pe-4 mb-4">
                <div class="row">
                    <partial name="Components/_FavoritesList" model="@Model.Favorites" />
                </div>
            </div>
            <div class="col-sm-12 col-md-10">
                <partial name="Components/_PostsFilter" model="@Model.FilterModel" />
                <partial name="Components/_PostsShowcase" model="@Model.PostsShowcase" />
                @if (Model.Pagination.TotalPages > 1)
                {
                    <partial name="Components/_Pagination" model="@Model.Pagination" />
                }
            </div>
        </div>
    </div>

@section Scripts{
    <script src="~/js/button_follow.js"></script>
    <script src="~/js/posts_filter.js"></script>
    @if (Model.Pagination.TotalPages > 1)
    {
        <script src="~/js/pagination.js"></script>
    }
}
}
else
{
    <div class="container mt-5">
        <partial name="Components/_NoResults" model="@String.Format("You don't follow anyone")"/>
    </div>
}

BlogSite/Pages/Author/Index.cshtml
@page
@model BlogSite.Pages.Author.IndexModel
@{
    ViewData["Title"] = Model.Author != null ? Model.Author.AuthorName : "No results";
}

@if(Model.Author != null)
{
    @section Css{
        <link rel="stylesheet" href="~/css/posts_filter.css" />
        <link rel="stylesheet" href="~/css/partial_post.css" />
    }

    <div class="container bg-secondary text-light rounded-3 p-3 mt-3">
        <div class="row mb-2">
            <div class="col-md-2 w-auto">
                <h5>@Model.Author.AuthorName</h5>
            </div>
            @if (Model.IsAuthenticated && !Model.IsClientBlog)
            {
                <div id="btn-follow-container" class="col-md-2 w-auto" style="margin-top: -1px;">
                    <partial name="Components/_ButtonFollow" model="@Model.Author.IsFollowed" />
                </div>
            }
        </div>
        <div class="row">
            <div class="col-md-2 w-auto">
                <h6>#@Model.Author.AuthorId</h6>
            </div>
            <div class="col-md-2 w-auto">
                <h6>Followers: @Model.Author.TotalFollowers</h6>
            </div>
            <div class="col-md-2 w-auto">
                <h6>Following: @Model.Author.TotalFollowing</h6>
            </div>
            <div class="col-md-2 w-auto">
                <h6>Likes: @Model.Author.TotalLikes</h6>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <partial name="Components/_PostsFilter" model="@Model.FilterModel" />
        <partial name="Components/_PostsShowcase" model="@Model.PostsShowcase" />
        @if (Model.Pagination.TotalPages > 1)
        {
            <partial name="Components/_Pagination" model="@Model.Pagination" />
        }
    </div>

    @section Scripts{
        <script src="~/js/posts_filter.js"></script>
        @if (Model.Pagination.TotalPages > 1){<script src="~/js/pagination.js"></script>}

        @if(Model.IsAuthenticated)
        {
            <script type="text/javascript">
                var authorId = @Model.Author.AuthorId;
            </script>

            <script src="~/js/button_follow.js"></script>
        }
    }
}
else
{
    <div class="container mt-5">
        <partial name="Components/_NoResults" model="null"/>
    </div>
}

BlogSite/Pages/Author/Settings.cshtml
@page
@model BlogSite.Pages.Author.SettingsModel
@{
    ViewData["Title"] = "Profile settings";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-4 p-4 p-md-5 border rounded-3 bg-light">
            <form method="post" asp-page-handler="Update">
                <h2 class="text-center mb-4">Profile settings</h2>
                <div class="form-group mb-4">
                    <label class="form-label" asp-for="@Model.Client.Username"></label>
                    <input class="form-control" type="text" id="username" placeholder="Change your username" asp-for="@Model.Client.Username">
                    <span class="text-danger" asp-validation-for="@Model.Client.Username"></span>
                </div>
                <div class="form-group mb-4">
                    <label class="form-label" asp-for="@Model.Client.Email"></label>
                    <input class="form-control" type="email" id="email" asp-for="@Model.Client.Email" disabled>
                </div>
                <div class="form-group mb-4">
                    <label class="form-label" asp-for="@Model.Client.Password"></label>
                    <input class="form-control" type="text" id="password" placeholder="Change your password" asp-for="@Model.Client.Password">
                    <span class="text-danger" asp-validation-for="@Model.Client.Password"></span>
                </div>
                <button type="submit" class="btn btn-danger w-100">Save changes</button>
            </form>
            <button id="btn-delete-acc" class="btn btn-secondary w-100 mt-3">Delete Account</button>
        </div>
    </div>
</div>

<partial name="Components/Modals/_DeleteAccountModal"/>

@section Scripts
{
    <script src="~/js/modals/delete_account_modal.js"></script>
    <partial name="_ValidationScriptsPartial" />
}